apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruit-service
  namespace: recruit-service
  labels:
    app: recruit-service
spec:
  replicas: 1
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app: recruit-service
  template:
    metadata:
      labels:
        app: recruit-service
    spec:
      containers:
        - name: recruit-service
          image: gyurihwang/contest-18-image-recruit:{BUILD_DATE_TIME}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: TZ
              value: "Asia/Seoul"
          envFrom:
            - secretRef:
                name: recruit-service-secret
            - secretRef:
                name: recruit-db-secret
          resources:
            requests:
              cpu: 150m
              memory: 384Mi
            limits:
              cpu: 300m
              memory: 768Mi

---
apiVersion: v1
kind: Service
metadata:
  name: recruit-service
  namespace: recruit-service
spec:
  selector:
    app: recruit-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recruit-ingress
  namespace: recruit-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - recruit.paassible.kro.kr
      secretName: recruit-tls
  rules:
    - host: recruit.paassible.kro.kr
      http:
        paths:
          - path: /recruits
            pathType: Prefix
            backend:
              service:
                name: recruit-service
                port:
                  number: 8080
