spring:
  application:
    name: board-service
  datasource:
    url: ${BOARD_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${BOARD_DB_USERNAME}
    password: ${BOARD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /boards/v3/api-docs
  swagger-ui:
    path: /boards/swagger-ui.html

user-service:
  url: http://user-service:8080

chat-service:
  url: http://chat-service:8080

meet-service:
  url: http://meet-service:8080

recruit-service:
  url: http://recruit-service:8080

google:
  gemini:
    api-key: ${GEMINI_API_KEY}