spring:
  application:
    name: meet-service
  datasource:
    url: ${MEET_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${MEET_DB_USERNAME}
    password: ${MEET_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8080

springdoc:
  api-docs:
    path: /meets/v3/api-docs
  swagger-ui:
    path: /meets/swagger-ui.html


user-service:
  url: http://user-service:8080

chat-service:
  url: http://chat-service:8080

board-service:
  url: http://board-service:8080

recruit-service:
  url: http://recruit-service:8080


livekit:
  url: ${LIVEKIT_URL}
  api:
    key: ${LIVEKIT_API_KEY}
    secret: ${LIVEKIT_API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
