spring:
  application:
    name: recruit-service
  datasource:
    url: ${RECRUIT_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RECRUIT_DB_USERNAME}
    password: ${RECRUIT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8080

springdoc:
  api-docs:
    path: /recruits/v3/api-docs
  swagger-ui:
    path: /recruits/swagger-ui.html


user-service:
  url: http://user-service:8080

chat-service:
  url: http://chat-service:8080

meet-service:
  url: http://meet-service:8080

board-service:
  url: http://board-service:8080

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
