spring:
  application:
    name: chat-service
  datasource:
    url: ${CHAT_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${CHAT_DB_USERNAME}
    password: ${CHAT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: 6000


  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8080

springdoc:
  api-docs:
    path: /chats/v3/api-docs
  swagger-ui:
    path: /chats/swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

nhncloud:
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    endpoint: ${S3_ENDPOINT}
    region: ${S3_REGION}
    bucket: ${S3_BUCKET}
    tenant-id: ${S3_TENANT_ID}

user-service:
  url: http://user-service.user-service:8080

meet-service:
  url: http://meet-service.meet-service:8080

board-service:
  url: http://board-service.board-service:8080

recruit-service:
  url: http://recruit-service.recruit-service:8080
